# Generated by Django 5.0.4 on 2025-03-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_studentinfomodel_teacherinfomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinfomodel',
            name='roll',
        ),
    ]
